<a href="https://colab.research.google.com/github/tunahanozdogan/Assignments/blob/main/Stats_Assign_(Central_Tendency%26_Dispersion).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Descriptive Statistics

 Import **NumPy**, **SciPy**, and **Pandas**

In [7]:
import numpy as np
import pandas as pd
import seaborn as sns
from scipy import stats
import statistics

 Randomly generate 1,000 samples from the normal distribution using `np.random.normal()`(mean = 100, standard deviation = 15)

np.random.normal(loc=0.0, scale=1.0, size=None)  #you need to modify this code.

loc will be equal to mean, scale will be equal to std deviation, size will be equal to sample size.

In [8]:
samples = np.random.normal(loc=100, scale=15, size=1000)

Compute the **mean**, **median**, and **mode**

In [9]:
mean = np.mean(samples)
median =np.median(samples)
mode = stats.mode(samples)

print(f"Mean value of samples: {mean}")
print(f"Median value of samples: {median}")
print(f"Mode value of samples: {mode}")

Mean value of samples: 100.52706547079231
Median value of samples: 100.82646795032585
Mode value of samples: ModeResult(mode=array([52.78404345]), count=array([1]))


Compute the **min**, **max**, **Q1**, **Q3**, and **interquartile range**

In [10]:
min = min(samples)
max = max(samples)
q1 = np.percentile(samples, 25)
q3 = np.percentile(samples, 75)
iqr = q3 - q1

print(f"Min value of samples: {min}")
print(f"Max value of samples: {max}")
print(f"q1 value of samples: {q1}")
print(f"q3 value of samples: {q3}")
print(f"IQR value of samples: {iqr}")

Min value of samples: 52.7840434524445
Max value of samples: 143.11775717198157
q1 value of samples: 90.6600625467122
q3 value of samples: 110.16575847373616
IQR value of samples: 19.505695927023964


Compute the **variance** and **standard deviation**

In [11]:
variance = statistics.variance(samples)
std_dev = statistics.stdev(samples)
print(f"Variance : {variance}")
print(f"standart devision: {std_dev}")

Variance : 210.11943825449197
standart devision: 14.495497171690662


Compute the **skewness** and **kurtosis**

You can use [`scipy.stats.skew`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.skew.html) and [`scipy.stats.kurtosis`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.kurtosis.html)

In [13]:
skewness = stats.skew(samples)
kurtosis = stats.kurtosis(samples)
print("skewness", skewness)
print("kurtosis", kurtosis)

skewness -0.09349055993803042
kurtosis -0.12279981984479749


## NumPy Correlation Calculation

Create an array x of integers between 10 (inclusive) and 20 (exclusive). Use `np.arange()`

In [14]:
x = np.arange(10,20)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

Then use `np.array()` to create a second array y containing 10 arbitrary integers.

In [15]:
y = np.array([1, 3, 5, 6, 8, 5, 7, 6, 9, 10])
y

array([ 1,  3,  5,  6,  8,  5,  7,  6,  9, 10])

Once you have two arrays of the same length, you can compute the **correlation coefficient** between x and y

In [16]:
r = np.corrcoef(x,y)
r

array([[1.        , 0.86732334],
       [0.86732334, 1.        ]])

## Pandas Correlation Calculation

Run the code below

In [17]:
x = pd.Series(range(10, 20))
y = pd.Series([2, 1, 4, 5, 8, 12, 18, 25, 96, 48])

Call the relevant method  to calculate Pearson's r correlation.

In [18]:
stats.pearsonr(x, y) # Pearson's r

(0.758640289091187, 0.010964341301680813)

OPTIONAL. Call the relevant method to calculate Spearman's rho correlation.

In [19]:
from scipy.stats import spearmanr

In [20]:
rho = spearmanr(x, y)
rho

SpearmanrResult(correlation=0.9757575757575757, pvalue=1.4675461874042197e-06)

## Seaborn Dataset Tips

Import Seaborn Library

In [21]:
import seaborn as sns

Load "tips" dataset from Seaborn

In [23]:
tips = sns.load_dataset("tips")

Generate descriptive statistics include those that summarize the central tendency, dispersion

In [24]:
tips.mode()

total_bill  tip   sex smoker  day    time  size
0       13.42  2.0  Male     No  Sat  Dinner     2

Call the relevant method to calculate pairwise Pearson's r correlation of columns (plus heatmap)

In [25]:
tips.median(numeric_only= True)

total_bill    17.795
tip            2.900
size           2.000
dtype: float64